services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_php
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: php -S 0.0.0.0:8000 -t public

  composer:
    image: composer:2
    container_name: symfony_composer
    volumes:
      - ./app:/app
    working_dir: /app

  db:
    image: mysql:8
    container_name: symfony_db
    restart: always
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata: